### ISSUE TITLE
Extra attribute in fmiModelDescription

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [CATIA-Systems/dymola-fmi-compatibility#1]
The modelDescription.xml in CoupledClutches_fmi3_Cvode.fmu contains 'xmlns:xsi' attribute which is not listed in the spec:
   2 <fmiModelDescription
   3   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

**Comment by KarlWernersson** [comment]
This is not an issue.
This is kind of a pseudo attribute to define common concepts with the xml and for the xsd.

I have made a ticket https://github.com/modelica/fmi-standard/issues/1929
Hoping someone can explain it better there.
