### ISSUE TITLE
ModelExchange FMU doesn't allow fmi3GetEventIndicators call

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [CATIA-Systems/dymola-fmi-compatibility#2]
The CVode version of the ModelExchange FMU errors out in Initialization mode with:
`FMU(3) IllegalFunctionCall: fmi3GetEventIndicators: fmi2ExitInitializationMode must be called before calling fmi3GetEventIndicators`
According to the [3.0.1 specification](https://fmi-standard.org/docs/3.0.1/#InitializationMode), this call is allowed in Initialization mode.

**Comment by t-sommer** [comment]
@KarlWernersson, can you take a look at this?

**Comment by t-sommer** [comment]
@Maplesoft-fmigroup, can you check if the problem persists with 03539ad35c0acdf258810151cfba294d2a714419?

**Comment by KarlWernersson** [comment]
I would suppose so that release was already build just before this was reported.
I can fix it for the fix pack.
As this is not allowed in FMI2, its imply a miss for FMI 3, should not be an issue to update.
Why did we change this? we had long discussions in FMI 2 where we decided that it was best to not allow this until after initialization as the values aren't relevant before. no problem for me to change and give them though.

**Comment by Maplesoft-fmigroup** [comment]
@KarlWernersson  This call is/was allowed in FMI2 and was discussed [here](https://github.com/modelica/fmi-standard/issues/395)
@t-sommer The new FMU does not fix the problem but I just noticed that there's an issue even before the call to fmi3GetEventIndicators in fmi3EnterInitializationMode:
`FMU(1) IllegalFunctionCall: fmi3EnterInitializationMode: tolerance control not supported for fmi3ModelExchange, setting toleranceDefined to fmi3False`
Is there a reason we can't use toleranceDefined=fmi3True for the ME FMU?

**Comment by KarlWernersson** [comment]
> @KarlWernersson This call is/was allowed in FMI2 and was discussed https://github.com/modelica/fmi-standard/issues/395

hehe, sorry I remembered the opposite, then I need to fix it for both versions
> Is there a reason we can't use toleranceDefined=fmi3True for the ME FMU?

Yes, we set these tolerances very tight and don't want anyone to change that
