### ISSUE TITLE
Reference plots

### ISSUE THREAD

**Issue by Maplesoft-fmigroup** [CATIA-Systems/dymola-fmi-compatibility#4]
@KarlWernersson  Could you please provide reference plots for one of the CoupledClutches FMUs? Our MapleSim results match the results from 'fmusim' but they don't look quite right (especially the first 2 outputs) compared to CoupledClutches results from other vendors (or your results from the 2019FD01 release).

**Comment by t-sommer** [comment]
By "reference plots", do you mean the results when the Modelica model is simulated in Dymola?

**Comment by Maplesoft-fmigroup** [comment]
@t-sommer  yes, that would be great.  The simulation results even for FMI2 don't look like they did in previous versions of Dymola. I just want to confirm that's expected.
